services:
  db:
    image: postgres:15
    container_name: rif_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  odoo:
    image: odoo:17
    container_name: rif_odoo
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      HOST: db
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8069:8069"
    volumes:
      - odoo-filestore:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    networks:
      - backend
    

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
  odoo-filestore: